// Mocks generated by Mockito 5.4.6 from annotations
// in escaner_1/test/provider/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i4;
import 'package:escaner_1/data/datasources/auth_api_datasource.dart' as _i2;
import 'package:escaner_1/data/services/auth_token_storage.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthTokens_0 extends _i1.SmartFake implements _i2.AuthTokens {
  _FakeAuthTokens_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApiDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiDatasource extends _i1.Mock implements _i2.AuthApiDatasource {
  MockAuthApiDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.AuthTokens> login(
    String? username,
    String? password, {
    _i4.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #login,
              [username, password],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i3.Future<_i2.AuthTokens>.value(
              _FakeAuthTokens_0(
                this,
                Invocation.method(
                  #login,
                  [username, password],
                  {#cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i3.Future<_i2.AuthTokens>);

  @override
  _i3.Future<_i2.AuthTokens> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i3.Future<_i2.AuthTokens>.value(
              _FakeAuthTokens_0(this, Invocation.method(#refreshToken, [])),
            ),
          )
          as _i3.Future<_i2.AuthTokens>);

  @override
  _i3.Future<bool> verifyToken(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#verifyToken, [accessToken]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [AuthTokenStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthTokenStorage extends _i1.Mock implements _i5.AuthTokenStorage {
  MockAuthTokenStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveTokens({
    required String? accessToken,
    required String? refreshToken,
    required int? expiresInSeconds,
    String? username,
    Map<String, dynamic>? userData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [], {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #expiresInSeconds: expiresInSeconds,
              #username: username,
              #userData: userData,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> getUsername() =>
      (super.noSuchMethod(
            Invocation.method(#getUsername, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<Map<String, dynamic>?> getUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, []),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<bool> isTokenValid() =>
      (super.noSuchMethod(
            Invocation.method(#isTokenValid, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> savePassword(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#savePassword, [password]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getPassword() =>
      (super.noSuchMethod(
            Invocation.method(#getPassword, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> clearPassword() =>
      (super.noSuchMethod(
            Invocation.method(#clearPassword, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveRememberMe(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveRememberMe, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> getRememberMe() =>
      (super.noSuchMethod(
            Invocation.method(#getRememberMe, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AuthTokens].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthTokens extends _i1.Mock implements _i2.AuthTokens {
  MockAuthTokens() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get accessToken =>
      (super.noSuchMethod(
            Invocation.getter(#accessToken),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#accessToken),
            ),
          )
          as String);

  @override
  String get refreshToken =>
      (super.noSuchMethod(
            Invocation.getter(#refreshToken),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#refreshToken),
            ),
          )
          as String);

  @override
  int get expiresIn =>
      (super.noSuchMethod(Invocation.getter(#expiresIn), returnValue: 0)
          as int);

  @override
  String get tokenType =>
      (super.noSuchMethod(
            Invocation.getter(#tokenType),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#tokenType),
            ),
          )
          as String);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
