// Mocks generated by Mockito 5.4.6 from annotations
// in escaner_1/test/provider/persona_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i6;
import 'package:escaner_1/data/services/persona_cache_service.dart' as _i5;
import 'package:escaner_1/domain/entities/persona.dart' as _i4;
import 'package:escaner_1/domain/repositories/persona_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePersonaSyncResult_0 extends _i1.SmartFake
    implements _i2.PersonaSyncResult {
  _FakePersonaSyncResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PersonaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonaRepository extends _i1.Mock implements _i2.PersonaRepository {
  MockPersonaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Persona>> getAllPersonas({bool? forceRefresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllPersonas, [], {
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i3.Future<List<_i4.Persona>>.value(<_i4.Persona>[]),
          )
          as _i3.Future<List<_i4.Persona>>);

  @override
  _i3.Future<_i2.PersonaSyncResult> syncPersonas({
    _i2.SyncProgressCallback? onProgress,
    _i6.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncPersonas, [], {
              #onProgress: onProgress,
              #cancelToken: cancelToken,
            }),
            returnValue: _i3.Future<_i2.PersonaSyncResult>.value(
              _FakePersonaSyncResult_0(
                this,
                Invocation.method(#syncPersonas, [], {
                  #onProgress: onProgress,
                  #cancelToken: cancelToken,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.PersonaSyncResult>);

  @override
  _i3.Future<_i4.Persona?> findByCodigoSolapin(String? codigo) =>
      (super.noSuchMethod(
            Invocation.method(#findByCodigoSolapin, [codigo]),
            returnValue: _i3.Future<_i4.Persona?>.value(),
          )
          as _i3.Future<_i4.Persona?>);

  @override
  _i3.Future<_i4.Persona?> findBySolapin(String? solapin) =>
      (super.noSuchMethod(
            Invocation.method(#findBySolapin, [solapin]),
            returnValue: _i3.Future<_i4.Persona?>.value(),
          )
          as _i3.Future<_i4.Persona?>);

  @override
  _i3.Future<bool> hasCache() =>
      (super.noSuchMethod(
            Invocation.method(#hasCache, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [PersonaCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonaCacheService extends _i1.Mock
    implements _i5.PersonaCacheService {
  MockPersonaCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Persona>> loadCache() =>
      (super.noSuchMethod(
            Invocation.method(#loadCache, []),
            returnValue: _i3.Future<List<_i4.Persona>>.value(<_i4.Persona>[]),
          )
          as _i3.Future<List<_i4.Persona>>);

  @override
  _i3.Future<void> saveCache(List<_i4.Persona>? personas) =>
      (super.noSuchMethod(
            Invocation.method(#saveCache, [personas]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveCacheWithMeta(
    List<_i4.Persona>? personas,
    _i5.SyncMeta? meta,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveCacheWithMeta, [personas, meta]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.SyncMeta?> loadMeta() =>
      (super.noSuchMethod(
            Invocation.method(#loadMeta, []),
            returnValue: _i3.Future<_i5.SyncMeta?>.value(),
          )
          as _i3.Future<_i5.SyncMeta?>);

  @override
  _i3.Future<void> saveMeta(_i5.SyncMeta? meta) =>
      (super.noSuchMethod(
            Invocation.method(#saveMeta, [meta]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
